In [25]:
import pandas as pd
import re
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_percentage_error
import wandb
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report


In [26]:
data_path = "SoftwareEngineer_cleaned.csv"
df = pd.read_csv(data_path)
print(df.shape)
df.head()

(34012, 12)


title level    company  yearsofexperience  \
0  Software Engineer  SE 2       eBay                5.0   
1  Software Engineer    60  Microsoft                5.0   
2  Software Engineer    63  Microsoft                8.5   
3  Software Engineer    62  Microsoft                4.0   
4  Software Engineer    59  Microsoft                3.0   

   totalyearlycompensation gender  Doctorate_Degree  Masters_Degree  \
0                   100000    NaN                 0               0   
1                   157000    NaN                 0               0   
2                   208000    NaN                 0               0   
3                   156000    NaN                 0               0   
4                   120000    NaN                 0               0   

   Bachelors_Degree  tag state           city  
0                 0  NaN    CA  San Francisco  
1                 0  NaN    CA  Mountain View  
2                 0  NaN    WA        Seattle  
3                 0  NaN    WA        Seattle  
4                 0  NaN    WA        Redmond

In [27]:
headers1 = ["company", "yearsofexperience", "Doctorate_Degree", "Masters_Degree", "Bachelors_Degree", "state", "city", "tag", "gender", 'level', "totalyearlycompensation"]
cat = ["company", "state", "city", "tag", "gender", 'level']
df_clean = df[headers1]
df_clean

company  yearsofexperience  Doctorate_Degree  Masters_Degree  \
0            eBay                5.0                 0               0   
1       Microsoft                5.0                 0               0   
2       Microsoft                8.5                 0               0   
3       Microsoft                4.0                 0               0   
4       Microsoft                3.0                 0               0   
...           ...                ...               ...             ...   
34007      Google               10.0                 0               0   
34008   Microsoft                2.0                 0               0   
34009        MSFT               14.0                 0               0   
34010  Salesforce                8.0                 0               0   
34011       apple                0.0                 0               0   

       Bachelors_Degree state           city                             tag  \
0                     0    CA  San Francisco                             NaN   
1                     0    CA  Mountain View                             NaN   
2                     0    WA        Seattle                             NaN   
3                     0    WA        Seattle                             NaN   
4                     0    WA        Redmond                             NaN   
...                 ...   ...            ...                             ...   
34007                 0    WA        Seattle  Distributed Systems (Back-End)   
34008                 0    WA        Redmond                      Full Stack   
34009                 0    WA        Seattle                      Full Stack   
34010                 0    CA  San Francisco                             iOS   
34011                 0    CA      Sunnyvale                         ML / AI   

      gender     level  totalyearlycompensation  
0        NaN      SE 2                   100000  
1        NaN        60                   157000  
2        NaN        63                   208000  
3        NaN        62                   156000  
4        NaN        59                   120000  
...      ...       ...                      ...  
34007    NaN        T4                   327000  
34008    NaN        62                   237000  
34009    NaN        63                   220000  
34010    NaN  Lead MTS                   280000  
34011   Male      ict3                   200000  

[34012 rows x 11 columns]

In [28]:
dfcat = df_clean

dfcat1 = df_clean[df_clean["totalyearlycompensation"] <= 50000]
dfcat1["salarycat"] = 1

dfcat2 = df_clean[(df_clean["totalyearlycompensation"] <= 100000) & (df_clean["totalyearlycompensation"] > 50000)]
dfcat2["salarycat"] = 2

dfcat3 = df_clean[(df_clean["totalyearlycompensation"] <= 150000) & (df_clean["totalyearlycompensation"] > 100000)]
dfcat3["salarycat"] = 3

dfcat4 = df_clean[(df_clean["totalyearlycompensation"] <= 200000) & (df_clean["totalyearlycompensation"] > 150000)]
dfcat4["salarycat"] = 4

dfcat5 = df_clean[(df_clean["totalyearlycompensation"] <= 250000) & (df_clean["totalyearlycompensation"] > 200000)]
dfcat5["salarycat"] = 5

dfcat6 = df_clean[(df_clean["totalyearlycompensation"] <= 300000) & (df_clean["totalyearlycompensation"] > 250000)]
dfcat6["salarycat"] = 6

dfcat7 = df_clean[(df_clean["totalyearlycompensation"] <= 350000) & (df_clean["totalyearlycompensation"] > 300000)]
dfcat7["salarycat"] = 7

dfcat8 = df_clean[(df_clean["totalyearlycompensation"] <= 400000) & (df_clean["totalyearlycompensation"] > 350000)]
dfcat8["salarycat"] = 8

dfcat9 = df_clean[(df_clean["totalyearlycompensation"] <= 500000) & (df_clean["totalyearlycompensation"] > 400000)]
dfcat9["salarycat"] = 9

dfcat10 = df_clean[(df_clean["totalyearlycompensation"] <= 600000) & (df_clean["totalyearlycompensation"] > 500000)]
dfcat10["salarycat"] = 10

dfcat11 = df_clean[(df_clean["totalyearlycompensation"] <= 700000) & (df_clean["totalyearlycompensation"] > 600000)]
dfcat11["salarycat"] = 11

dfcat12 = df_clean[(df_clean["totalyearlycompensation"] <= 800000) & (df_clean["totalyearlycompensation"] > 700000)]
dfcat12["salarycat"] = 12

dfcat13 = df_clean[(df_clean["totalyearlycompensation"] <= 900000) & (df_clean["totalyearlycompensation"] > 800000)]
dfcat13["salarycat"] = 13

dfcat14 = df_clean[(df_clean["totalyearlycompensation"] <= 1000000) & (df_clean["totalyearlycompensation"] > 900000)]
dfcat14["salarycat"] = 14



print(dfcat1.shape)
print(dfcat2.shape)
print(dfcat3.shape)
print(dfcat4.shape)
print(dfcat5.shape)
print(dfcat6.shape)
print(dfcat7.shape)
print(dfcat8.shape)
print(dfcat9.shape)
print(dfcat10.shape)
print(dfcat11.shape)
print(dfcat12.shape)
print(dfcat13.shape)
print(dfcat14.shape)

dfcat2

(17, 12)
(2006, 12)
(6450, 12)
(9663, 12)
(6143, 12)
(3642, 12)
(2136, 12)
(1454, 12)
(1477, 12)
(577, 12)
(252, 12)
(115, 12)
(58, 12)
(22, 12)


C:\Users\pedia\AppData\Local\Temp\ipykernel_13840\2633815590.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfcat1["salarycat"] = 1
C:\Users\pedia\AppData\Local\Temp\ipykernel_13840\2633815590.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfcat2["salarycat"] = 2
C:\Users\pedia\AppData\Local\Temp\ipykernel_13840\2633815590.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in th

company  yearsofexperience  Doctorate_Degree  Masters_Degree  \
0                eBay                5.0                 0               0   
28               Oath                5.0                 0               0   
125               IBM                3.0                 0               0   
216         Blackbaud                3.0                 0               0   
327               IBM                1.0                 0               0   
...               ...                ...               ...             ...   
33718      TransUnion                1.0                 0               0   
33719  General Motors                3.0                 0               0   
33724         Verizon                0.0                 0               0   
33725            USAA                0.0                 0               0   
33726  Morgan Stanley                1.0                 0               0   

       Bachelors_Degree state           city                          tag  \
0                     0    CA  San Francisco                          NaN   
28                    0    MD      Baltimore                          NaN   
125                   0    TX         Austin                          NaN   
216                   0    SC     Charleston                          NaN   
327                   0    NY       New York  Web Development (Front-End)   
...                 ...   ...            ...                          ...   
33718                 0    IL        Chicago                       DevOps   
33719                 0    MI        Detroit                   Full Stack   
33724                 0    GA        Atlanta                       DevOps   
33725                 0    TX    San Antonio                   Full Stack   
33726                 0    NY       New York                   Full Stack   

      gender                  level  totalyearlycompensation  salarycat  
0        NaN                   SE 2                   100000          2  
28       NaN                    IC2                    88000          2  
125      NaN                      7                    84000          2  
216     Male                    SE1                    72000          2  
327     Male                 Band 6                    96000          2  
...      ...                    ...                      ...        ...  
33718   Male                 Senior                    87000          2  
33719   Male                     L5                    88000          2  
33724    NaN                  MTS I                    72000          2  
33725   Male  Software Engineer III                    72000          2  
33726   Male                Analyst                   100000          2  

[2006 rows x 12 columns]

In [29]:
frames = [dfcat1, dfcat2, dfcat3, dfcat4, dfcat5, dfcat6, dfcat7, dfcat8, dfcat9, dfcat10, dfcat11, dfcat12, dfcat13, dfcat14]

result = pd.concat(frames)

result

company  yearsofexperience  Doctorate_Degree  Masters_Degree  \
6696           Accenture                1.0                 0               0   
9068   Ultimate Software                0.0                 0               0   
10452                IBM                0.0                 0               0   
10498          Accenture                1.0                 0               0   
19798           Raytheon                1.0                 0               0   
...                  ...                ...               ...             ...   
24551             Oracle               25.0                 0               1   
26962             Google               21.0                 0               1   
27446           Facebook               15.0                 1               0   
30936           Facebook                6.0                 0               0   
33139             Google                8.0                 1               0   

       Bachelors_Degree state           city                             tag  \
6696                  0    TX    San Antonio                      Full Stack   
9068                  0    FL         Weston                  Testing (SDET)   
10452                 0    GA        Atlanta                      Full Stack   
10498                 0    OH       Columbus                      Full Stack   
19798                 0    NH         Pelham     Web Development (Front-End)   
...                 ...   ...            ...                             ...   
24551                 0    CA   Redwood City                      Full Stack   
26962                 0    CA  Mountain View  Distributed Systems (Back-End)   
27446                 0    WA        Redmond                      Full Stack   
30936                 1    CA     Menlo Park                         ML / AI   
33139                 0    CA  Mountain View                         ML / AI   

      gender                        level  totalyearlycompensation  salarycat  
6696    Male                           12                    50000          1  
9068    Male                Part Time SE1                    35000          1  
10452   Male                   Apprentice                    47000          1  
10498   Male  Associate Software Engineer                    46000          1  
19798    NaN                           l1                    50000          1  
...      ...                          ...                      ...        ...  
24551   Male                           VP                   950000         14  
26962    NaN                           L7                   929000         14  
27446    NaN                          IC7                   940000         14  
30936   Male                           E7                   987000         14  
33139    NaN                           L5                   961000         14  

[34012 rows x 12 columns]

In [30]:
cat = ["company", "state", "city", "tag", "gender", 'level']
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(result[cat]), index=result.index)

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(cat)
encode_df.head()

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


company_10x Genomics  company_23andMe  company_2U  company_3M  \
6696                    0.0              0.0         0.0         0.0   
9068                    0.0              0.0         0.0         0.0   
10452                   0.0              0.0         0.0         0.0   
10498                   0.0              0.0         0.0         0.0   
19798                   0.0              0.0         0.0         0.0   

       company_3m  company_7-Eleven  company_7-eleven  company_8x8  \
6696          0.0               0.0               0.0          0.0   
9068          0.0               0.0               0.0          0.0   
10452         0.0               0.0               0.0          0.0   
10498         0.0               0.0               0.0          0.0   
19798         0.0               0.0               0.0          0.0   

       company_ABB  company_ADP  ...  level_unknown  level_vice president  \
6696           0.0          0.0  ...            0.0                   0.0   
9068           0.0          0.0  ...            0.0                   0.0   
10452          0.0          0.0  ...            0.0                   0.0   
10498          0.0          0.0  ...            0.0                   0.0   
19798          0.0          0.0  ...            0.0                   0.0   

       level_x2  level_x4  level_x5  level_x6  level_x7  level_z4  level_||  \
6696        0.0       0.0       0.0       0.0       0.0       0.0       0.0   
9068        0.0       0.0       0.0       0.0       0.0       0.0       0.0   
10452       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
10498       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
19798       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

       level_nan  
6696         0.0  
9068         0.0  
10452        0.0  
10498        0.0  
19798        0.0  

[5 rows x 4211 columns]

In [31]:
result = result.merge(encode_df,left_index=True, right_index=True)
result = result.drop(cat,1)
result# Merge one-hot encoded features and drop the originals
result

C:\Users\pedia\AppData\Local\Temp\ipykernel_13840\138238806.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  result = result.drop(cat,1)


yearsofexperience  Doctorate_Degree  Masters_Degree  Bachelors_Degree  \
6696                 1.0                 0               0                 0   
9068                 0.0                 0               0                 0   
10452                0.0                 0               0                 0   
10498                1.0                 0               0                 0   
19798                1.0                 0               0                 0   
...                  ...               ...             ...               ...   
24551               25.0                 0               1                 0   
26962               21.0                 0               1                 0   
27446               15.0                 1               0                 0   
30936                6.0                 0               0                 1   
33139                8.0                 1               0                 0   

       totalyearlycompensation  salarycat  company_10x Genomics  \
6696                     50000          1                   0.0   
9068                     35000          1                   0.0   
10452                    47000          1                   0.0   
10498                    46000          1                   0.0   
19798                    50000          1                   0.0   
...                        ...        ...                   ...   
24551                   950000         14                   0.0   
26962                   929000         14                   0.0   
27446                   940000         14                   0.0   
30936                   987000         14                   0.0   
33139                   961000         14                   0.0   

       company_23andMe  company_2U  company_3M  ...  level_unknown  \
6696               0.0         0.0         0.0  ...            0.0   
9068               0.0         0.0         0.0  ...            0.0   
10452              0.0         0.0         0.0  ...            0.0   
10498              0.0         0.0         0.0  ...            0.0   
19798              0.0         0.0         0.0  ...            0.0   
...                ...         ...         ...  ...            ...   
24551              0.0         0.0         0.0  ...            0.0   
26962              0.0         0.0         0.0  ...            0.0   
27446              0.0         0.0         0.0  ...            0.0   
30936              0.0         0.0         0.0  ...            0.0   
33139              0.0         0.0         0.0  ...            0.0   

       level_vice president  level_x2  level_x4  level_x5  level_x6  level_x7  \
6696                    0.0       0.0       0.0       0.0       0.0       0.0   
9068                    0.0       0.0       0.0       0.0       0.0       0.0   
10452                   0.0       0.0       0.0       0.0       0.0       0.0   
10498                   0.0       0.0       0.0       0.0       0.0       0.0   
19798                   0.0       0.0       0.0       0.0       0.0       0.0   
...                     ...       ...       ...       ...       ...       ...   
24551                   0.0       0.0       0.0       0.0       0.0       0.0   
26962                   0.0       0.0       0.0       0.0       0.0       0.0   
27446                   0.0       0.0       0.0       0.0       0.0       0.0   
30936                   0.0       0.0       0.0       0.0       0.0       0.0   
33139                   0.0       0.0       0.0       0.0       0.0       0.0   

       level_z4  level_||  level_nan  
6696        0.0       0.0        0.0  
9068        0.0       0.0        0.0  
10452       0.0       0.0        0.0  
10498       0.0       0.0        0.0  
19798       0.0       0.0        0.0  
...         ...       ...        ...  
24551       0.0       0.0        0.0  
26962       0.0       0.0        0.0  
27446       0.0       0.0        0.0  
30936       0.0       0.0        0.0 

In [46]:
# Split our preprocessed data into our features and target arrays
y = result.salarycat
X = result.drop(columns=["salarycat"])

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, train_size=0.8)

In [47]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2'],
    'class_weight': [None, 'balanced']
}

In [48]:
clf = RandomForestClassifier(random_state = 42) 


In [49]:
grid_search = GridSearchCV(estimator=clf, param_grid=param_grid, cv=5)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Print the best parameters and the best score
print("Best parameters: ", grid_search.best_params_)
print("Best score: ", grid_search.best_score_)

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py:425: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for 

Best parameters:  {'class_weight': 'balanced', 'max_depth': 20, 'max_features': 'auto', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 300}
Best score:  0.6560339064722968


In [44]:
clf.fit(X_train, y_train)
# make predictions on the test set
y_pred = clf.predict(X_test)

# generate the classification report
class_names = [str(i) for i in range(1, 15)] # assuming that your classes are numbered from 1 to 14
print(classification_report(y_test, y_pred, target_names=class_names))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         3
           2       0.97      0.90      0.94       389
           3       0.97      0.97      0.97      1303
           4       0.94      0.99      0.97      1990
           5       0.86      0.94      0.89      1232
           6       0.74      0.75      0.75       707
           7       0.61      0.51      0.55       404
           8       0.51      0.43      0.47       278
           9       0.60      0.59      0.59       301
          10       0.59      0.38      0.46       115
          11       0.31      0.28      0.29        40
          12       0.89      0.33      0.48        24
          13       0.00      0.00      0.00        13
          14       0.00      0.00      0.00         4

    accuracy                           0.86      6803
   macro avg       0.57      0.50      0.53      6803
weighted avg       0.85      0.86      0.85      6803



C:\Users\pedia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\pedia\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [42]:
from sklearn.metrics import confusion_matrix

# generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   0    3    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0  359   28    2    0    0    0    0    0    0    0    0    0    0]
 [   0    5 1277   21    0    0    0    0    0    0    0    0    0    0]
 [   0    0    3 1972   14    0    0    1    0    0    0    0    0    0]
 [   0    0    0   46 1159   21    3    2    1    0    0    0    0    0]
 [   0    0    1   12  111  539   34    4    5    1    0    0    0    0]
 [   0    0    0    7   41   94  212   32   17    0    0    1    0    0]
 [   0    0    0    3   10   32   64  118   48    3    0    0    0    0]
 [   0    0    0    2   10   27   18   53  174    9    7    0    1    0]
 [   0    0    0    0    3    7    9   13   27   47    9    0    0    0]
 [   0    0    0    0    1    3    0    2   12   11    9    2    0    0]
 [   0    0    0    0    1    1    3    1    3    3    4    7    1    0]
 [   0    0    0    0    0    0    0    0    6    2    4    1    0    0]
 [   0    0    0    0    0    2    1    0    0    0

In [11]:
training_score = rf.score(X_train, y_train)
testing_score = rf.score(X_test, y_test)
mape = mean_absolute_percentage_error(y_test, y_pred)

print(f"Mean absolute percentage error: {mape}")
print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

Mean absolute percentage error: 0.20032167434692383
Training Score: 0.9024954978132236
Testing Score: 0.042628252241658095


In [12]:
r2 = r2_score(y_pred, y_test)
print("R-squared score: ", r2)

R-squared score:  0.4812088921116767


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# define a custom dataset class that inherits from PyTorch's Dataset class
class CustomDataset(Dataset):
    def __init__(self, dataframe):
        self.df = dataframe
        self.X = dataframe[['gender', 'years_of_experience', 'company', 'location']].values
        self.y = dataframe['class'].values
        
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# load your data into a pandas DataFrame
df = pd.read_csv('your_data.csv')

# split the data into training and testing sets
train_df, test_df = train_test_split(df, test_size=0.2)

# create training and test datasets using the custom dataset class
train_dataset = CustomDataset(train_df)
test_dataset = CustomDataset(test_df)

# create data loaders for the training and test datasets
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

# define the model architecture
class MultiClassModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(5, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 14)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# initialize the model, loss function, and optimizer
model = MultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

# train the model
for epoch in range(num_epochs):
    for X, y in train_loader:
        optimizer.zero_grad()
        output = model(X)
        loss = criterion(output, y)
        loss.backward()
        optimizer.step()

# evaluate the model on the test set
with torch.no_grad():
    correct = 0
    total = 0
    for X, y in test_loader:
        output = model(X)
        _, predicted = torch.max(output.data, 1)
        total += y.size(0)
        correct += (predicted == y).sum().item()
    print(f'Test accuracy: {100 * correct / total}%')